In [1]:
##2.2.1 텐서 다루기

In [1]:
import torch
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 2070'

In [2]:
import torch

USE_CUDA = torch.cuda.is_available()
device = torch.device('cuda:0' if USE_CUDA else 'cpu')

print('CUDA 사용 가능 여부 :', USE_CUDA)
print('현재 사용 device :', device)
print('CUDA Index :', torch.cuda.current_device())
print('GPU 이름 :', torch.cuda.get_device_name())
print('GPU 개수 :', torch.cuda.device_count())

CUDA 사용 가능 여부 : True
현재 사용 device : cuda:0
CUDA Index : 0
GPU 이름 : NVIDIA GeForce RTX 2070
GPU 개수 : 1


In [2]:
import torch
print(torch.tensor([[1,2],[3,4]]))
print('------------------------')
print(torch.tensor([[1,2],[3,4]], device="cuda:0")) #GPU가 없다면 오류가 발생하므로 주석 처리하였습니다.
print('------------------------')
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
------------------------
tensor([[1, 2],
        [3, 4]], device='cuda:0')
------------------------
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [10]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())
print('------------------------')

temp = torch.tensor([[1,2],[3,4]], device="cuda:0") #GPU가 없다면 오류가 발생하므로 주석 처리하였습니다.
print(temp.device)
#temp = torch.tensor([[1,2],[3,4]], device="cpu:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
------------------------
cuda:0
[[1 2]
 [3 4]]


In [11]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print('------------------------')
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [12]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

tensor([2, 2, 3])


In [13]:
temp = torch.tensor([
    [1, 2], [3, 4]
])

print(temp.shape)
print('------------------------')
print(temp.view(4,1))
print('------------------------')
print(temp.view(-1))
print('------------------------')
print(temp.view(1, -1))
print('------------------------')
print(temp.view(-1, 1))

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])


In [1]:
#2.4 파이토치 코드 맛보기

In [19]:
import torchvision.transforms as transforms

mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0),)
])

In [21]:
from six.moves import urllib    
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0')]
urllib.request.install_opener(opener)

In [23]:
from torchvision.datasets import MNIST
import requests
download_root='../chap02/data/MNIST_DATASET'

train_dataset=MNIST(download_root, transform=mnist_transform, train=True, download=True)

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:11<00:00, 885167.09it/s] 


Extracting ../chap02/data/MNIST_DATASET\MNIST\raw\train-images-idx3-ubyte.gz to ../chap02/data/MNIST_DATASET\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 146628.18it/s]


Extracting ../chap02/data/MNIST_DATASET\MNIST\raw\train-labels-idx1-ubyte.gz to ../chap02/data/MNIST_DATASET\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:02<00:00, 595475.26it/s]


Extracting ../chap02/data/MNIST_DATASET\MNIST\raw\t10k-images-idx3-ubyte.gz to ../chap02/data/MNIST_DATASET\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 910854.83it/s]

Extracting ../chap02/data/MNIST_DATASET\MNIST\raw\t10k-labels-idx1-ubyte.gz to ../chap02/data/MNIST_DATASET\MNIST\raw



In [3]:
from torch.optim import optimizer
import torch
import torch.nn as nn
from torch.optim import SGD, lr_scheduler
from torch.utils.data import DataLoader

# 데이터셋과 데이터로더를 정의해야 합니다.
# 예를 들어, 단순한 데이터셋을 만들고 데이터로더를 생성할 수 있습니다.
class SimpleDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# 예제 데이터를 생성합니다.
data = [(torch.randn(1), torch.randn(1)) for _ in range(100)]
# 데이터셋을 생성합니다.
dataset = SimpleDataset(data)
# 데이터로더를 생성합니다.
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

# 모델을 생성합니다.
def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features=in_features, out_features=hidden_features, bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
    net = nn.Sequential(hidden, activation, output)
    return net

# 모델을 생성합니다.
model = MLP()

# 손실 함수를 정의합니다.
criterion = nn.MSELoss()

# 옵티마이저를 정의합니다.
optimizer = SGD(model.parameters(), lr=0.01, momentum=0.9)

# 스케줄러를 정의합니다.
scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lambda epoch: 0.95**epoch)

# 모델 훈련 교재 57페이지
for epoch in range(1, 100+1):
    for x, y in dataloader:
        optimizer.zero_grad()
        loss = criterion(model(x), y)
        loss.backward()
        optimizer.step()
    scheduler.step()

# 학습 후의 모델을 사용하여 예측을 수행할 수 있습니다.
###
# 예측을 수행할 테스트 데이터를 정의합니다.
test_data = [(torch.randn(1), torch.randn(1)) for _ in range(10)]
print(test_data)
# 모델을 평가 모드로 설정합니다.
model.eval()

# 각 테스트 데이터에 대한 예측을 수행합니다.
with torch.no_grad():  # 그라디언트 계산 비활성화
    for x_test, y_test in test_data:
        # 입력 데이터를 모델에 전달하여 예측을 수행합니다.
        predicted_output = model(x_test)
        print("Input:", x_test)
        print("Actual Output:", y_test)
        print("Predicted Output:", predicted_output)

[(tensor([1.4710]), tensor([0.2173])), (tensor([0.1412]), tensor([1.7285])), (tensor([0.1344]), tensor([2.2867])), (tensor([-1.3283]), tensor([-0.5386])), (tensor([0.8748]), tensor([-0.3786])), (tensor([-2.9165]), tensor([0.5221])), (tensor([1.0283]), tensor([0.5626])), (tensor([1.5960]), tensor([-0.9997])), (tensor([-1.4951]), tensor([0.4893])), (tensor([1.2379]), tensor([0.4651]))]
Input: tensor([1.4710])
Actual Output: tensor([0.2173])
Predicted Output: tensor([-0.2049])
Input: tensor([0.1412])
Actual Output: tensor([1.7285])
Predicted Output: tensor([0.0911])
Input: tensor([0.1344])
Actual Output: tensor([2.2867])
Predicted Output: tensor([0.0922])
Input: tensor([-1.3283])
Actual Output: tensor([-0.5386])
Predicted Output: tensor([-0.0317])
Input: tensor([0.8748])
Actual Output: tensor([-0.3786])
Predicted Output: tensor([-0.0864])
Input: tensor([-2.9165])
Actual Output: tensor([0.5221])
Predicted Output: tensor([-0.5570])
Input: tensor([1.0283])
Actual Output: tensor([0.5626])
Pre

In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset = pd.read_csv(r'../chap02/data/car_evaluation.csv')

In [3]:
dataset.head()

price  maint doors persons lug_capacity safety output
0  vhigh  vhigh     2       2        small    low  unacc
1  vhigh  vhigh     2       2        small    med  unacc
2  vhigh  vhigh     2       2        small   high  unacc
3  vhigh  vhigh     2       2          med    low  unacc
4  vhigh  vhigh     2       2          med    med  unacc

In [4]:
fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 8
fig_size[1] = 6
plt.rcParams["figure.figsize"] = fig_size
dataset.output.value_counts().plot(kind='pie', autopct='%0.05f%%', colors=['lightblue', 'lightgreen', 'orange', 'pink'], explode=(0.05, 0.05, 0.05,0.05))

: 

In [3]:
categorical_columns = ['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety']

In [4]:
for category in categorical_columns:
    dataset[category] = dataset[category].astype('category')

In [5]:
price = dataset['price'].cat.codes.values
maint = dataset['maint'].cat.codes.values
doors = dataset['doors'].cat.codes.values
persons = dataset['persons'].cat.codes.values
lug_capacity = dataset['lug_capacity'].cat.codes.values
safety = dataset['safety'].cat.codes.values

categorical_data = np.stack([price, maint, doors, persons, lug_capacity, safety], 1)
categorical_data[:10]

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       [3, 3, 0, 0, 1, 1],
       [3, 3, 0, 0, 1, 2],
       [3, 3, 0, 0, 1, 0],
       [3, 3, 0, 0, 0, 1],
       [3, 3, 0, 0, 0, 2],
       [3, 3, 0, 0, 0, 0],
       [3, 3, 0, 1, 2, 1]], dtype=int8)

In [6]:
categorical_data = torch.tensor(categorical_data, dtype=torch.int64)
categorical_data[:10]

tensor([[3, 3, 0, 0, 2, 1],
        [3, 3, 0, 0, 2, 2],
        [3, 3, 0, 0, 2, 0],
        [3, 3, 0, 0, 1, 1],
        [3, 3, 0, 0, 1, 2],
        [3, 3, 0, 0, 1, 0],
        [3, 3, 0, 0, 0, 1],
        [3, 3, 0, 0, 0, 2],
        [3, 3, 0, 0, 0, 0],
        [3, 3, 0, 1, 2, 1]])

In [7]:
outputs = pd.get_dummies(dataset.output)
outputs = outputs.values
outputs = torch.tensor(outputs).flatten()

print(categorical_data.shape)
print(outputs.shape)

torch.Size([1728, 6])
torch.Size([6912])


In [8]:
categorical_column_sizes = [len(dataset[column].cat.categories) for column in categorical_columns]
categorical_embedding_sizes = [(col_size, min(50, (col_size+1)//2)) for col_size in categorical_column_sizes]
print(categorical_embedding_sizes)

[(4, 2), (4, 2), (4, 2), (3, 2), (3, 2), (3, 2)]


In [9]:
total_records = 1728
test_records = int(total_records * .2)

categorical_train_data = categorical_data[:total_records-test_records]
categorical_test_data = categorical_data[total_records-test_records:total_records]
train_outputs = outputs[:total_records-test_records]
test_outputs = outputs[total_records-test_records:total_records]

In [10]:
print(len(categorical_train_data))
print(len(train_outputs))
print(len(categorical_test_data))
print(len(test_outputs))

1383
1383
345
345


In [14]:
class Model(nn.Module):
    def __init__(self, embedding_size, output_size, layers, p=0.4):
        super().__init__()
        self.all_embeddings = nn.ModuleList([nn.Embedding(ni, nf) for ni, nf in embedding_size])
        self.embedding_dropout = nn.Dropout(p)
        
        all_layers = []
        num_categorical_cols = sum((nf for ni, nf in embedding_size))
        input_size = num_categorical_cols 

        for i in layers:
            all_layers.append(nn.Linear(input_size, i))
            all_layers.append(nn.ReLU(inplace=True))
            all_layers.append(nn.BatchNorm1d(i))
            all_layers.append(nn.Dropout(p))
            input_size = i

        all_layers.append(nn.Linear(layers[-1], output_size))
        self.layers = nn.Sequential(*all_layers)

    def forward(self, x_categorical):
        embeddings = []
        for i,e in enumerate(self.all_embeddings):
            embeddings.append(e(x_categorical[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.embedding_dropout(x)
        x = self.layers(x)
        return x

In [15]:
model = Model(categorical_embedding_sizes, 4, [200,100,50], p=0.4)
print(model)

Model(
  (all_embeddings): ModuleList(
    (0): Embedding(4, 2)
    (1): Embedding(4, 2)
    (2): Embedding(4, 2)
    (3): Embedding(3, 2)
    (4): Embedding(3, 2)
    (5): Embedding(3, 2)
  )
  (embedding_dropout): Dropout(p=0.4, inplace=False)
  (layers): Sequential(
    (0): Linear(in_features=12, out_features=200, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=200, out_features=100, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=100, out_features=50, bias=True)
    (9): ReLU(inplace=True)
    (10): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (11): Dropout(p=0.4, inplace=False)
    (12): Linear(in_features=50, out_features=4, bias=True)
  )
)


<ipython-input-14-2841aec1b83c>:9: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  num_categorical_cols = sum((nf for ni, nf in embedding_size))


In [16]:
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [17]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

In [18]:
epochs = 500
aggregated_losses = []
train_outputs = train_outputs.to(device=device, dtype=torch.int64)
for i in range(epochs):
    i += 1
    y_pred = model(categorical_train_data)
    single_loss = loss_function(y_pred, train_outputs)
    aggregated_losses.append(single_loss)

    if i%25 == 1:
        print(f'epoch: {i:3} loss: {single_loss.item():10.8f}')

    optimizer.zero_grad()
    single_loss.backward()
    optimizer.step()

print(f'epoch: {i:3} loss: {single_loss.item():10.10f}')

epoch:   1 loss: 1.65249419
epoch:  26 loss: 1.45879722
epoch:  51 loss: 1.33384025
epoch:  76 loss: 1.23400390
epoch: 101 loss: 1.11513293
epoch: 126 loss: 0.95979440
epoch: 151 loss: 0.86270565
epoch: 176 loss: 0.76592660
epoch: 201 loss: 0.72367680
epoch: 226 loss: 0.66824156
epoch: 251 loss: 0.64819992
epoch: 276 loss: 0.63562006
epoch: 301 loss: 0.61229289
epoch: 326 loss: 0.60510421
epoch: 351 loss: 0.59476370
epoch: 376 loss: 0.59021413
epoch: 401 loss: 0.59014261
epoch: 426 loss: 0.58325481
epoch: 451 loss: 0.57738525
epoch: 476 loss: 0.57660651
epoch: 500 loss: 0.5747064352


In [19]:
test_outputs = test_outputs.to(device=device, dtype=torch.int64)
with torch.no_grad():
    y_val = model(categorical_test_data)
    loss = loss_function(y_val, test_outputs)
print(f'Loss: {loss:.8f}')

Loss: 0.56376094


In [20]:
print(y_val[:5])

tensor([[ 1.6323,  0.8207, -2.8484, -2.7129],
        [ 3.1852,  1.6122, -4.3075, -4.0866],
        [ 2.1316,  1.0418, -3.4468, -3.0402],
        [ 1.8252,  0.8358, -3.0042, -2.6456],
        [ 2.1291,  1.2548, -2.8223, -2.7871]])


In [21]:
y_val = np.argmax(y_val, axis=1)
print(y_val[:5])

tensor([0, 0, 0, 0, 0])


In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(test_outputs,y_val))
print(classification_report(test_outputs,y_val))
print(accuracy_score(test_outputs, y_val))

[[259   0]
 [ 85   1]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86       259
           1       1.00      0.01      0.02        86

    accuracy                           0.75       345
   macro avg       0.88      0.51      0.44       345
weighted avg       0.81      0.75      0.65       345

0.7536231884057971
